version: '3.5'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql-2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - app_network
    volumes:
      - mysql-volume:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-2
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - ./src:/app/src

networks:
  app_network:

volumes:
  mysql-volume:
    driver: local